#!/bin/bash
# Status log with invalid UTF-8 bytes, trailing tabs, dotted keys, bad slugs, reopenings, and no final newline.
printf 'needs-decision [key=a] [at=100]: bad \xff byte\n'
printf 'needs-decision [key=b]: clean question\n'
printf 'resolved [key=b]: answered\n'
printf 'needs-decision [key=c] [at=10:30]: trunc \xe2\x80\n'
printf 'resolved [key=c]: done\n'
printf 'resolved [key=a]: done\n'
printf 'needs-decision [key=pending-reply-x1]: pending-reply-missed: caf\xe9\n'
printf 'blocked [key=tabby] [at=1790000000]: note ends in tabs\t\t\n'
printf 'needs-decision: keyless question caf\xc3\xa9\n'
printf 'blocked: [key=head.key] note-head key with dot\n'
printf 'needs-decision [key=headXkey]: must survive a dotted drop\n'
printf 'resolved [key=head.key]: closed dotted\n'
printf 'needs-decision [key=bad key]: invalid slug\n'
printf 'plain prose [at=10:30] with colon: not a transition\n'
printf 'needs-decision [key=re] [at=5]: first\n'
printf 'needs-decision [key=re] [at=1790000500]: reopened later\n'
printf 'captain-held [key=zz]: never opened\n'
printf 'needs-decision [key=bad2] [at=7]: bad \xff again\n'
printf 'blocked [key=last] [at=notanumber]: bad stamp no newline'
